services:
  db:
    env_file:
      - db.env
    environment: []
  api:
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,api,10.0.0.218,api.localhost,api.digidex.bio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saleor-api.rule=Host(`10.0.0.218`) && PathPrefix(`/graphql/`)"
      - "traefik.http.routers.saleor-api.entrypoints=web"
      - "traefik.http.routers.saleor-api.priority=100"
      - "traefik.http.routers.saleor-api.tls=false"
      - "traefik.http.routers.saleor-api.tls.certresolver="
      - "traefik.http.services.saleor-api.loadbalancer.server.port=8000"
  dashboard:
    ports:
      - "9000:80"
